language: objective-c

branches:
  only:
    - master
    
osx_image: xcode8.2
xcode_project: DataCache.xcodeproj
xcode_scheme: DataCache
xcode_sdk: iphonesimulator10.2

script:
- xcodebuild clean build test -project DataCache.xcodeproj -scheme DataCache
