language: objective-c
osx_image: xcode8

env:
  - iOS= PLATFORM=iOS DST='platform=iOS Simulator,name=iPhone 6S' ACTION=test
  - tvOS= PLATFORM=tvOS DST='platform=tvOS Simulator,name=Apple TV 1080p' ACTION=test
  - macOS= PLATFORM=Mac DST='platform=OS X' ACTION=test
  - watchOS= PLATFORM=watchOS DST='platform=watchOS Simulator,name=Apple Watch - 38mm' ACTION=build

install:
  - carthage bootstrap --platform $PLATFORM

script:
  - set -o pipefail && xcodebuild $ACTION -scheme JSONCache -destination "$DST" -derivedDataPath build | xcpretty

