language: objective-c
osx_image: xcode8.2
branches:
  only:
  - master
script:
- xcodebuild test -workspace DataCache.xcodeproj/project.xcworkspace -scheme DataCache -destination "platform=iOS Simulator,name=iPhone 7,OS=10.2"
