language: objective-c
osx_image: xcode8.1
branches:
  only:
  - master
script:
- xcodebuild test -workspace JSONCache.xcodeproj/project.xcworkspace -scheme JSONCache -destination "platform=iOS Simulator,name=iPhone 7 Plus,OS=10.1"
